dais/urls.py
from django.conf import settings
from django.conf.urls import url
from django.contrib import admin
from home.views import HomeView
from watch.views import WatchView
from look.views import LookView
from listen.views import ListenView
from django.conf.urls.static import static
from radio.views import RadioView, SoundView
from music.views import MusicView, ArtistView
from press.views import PressView
from about.views import AboutView
from team.views import TeamView
from django.views.generic import TemplateView
from django.conf.urls import include
urlpatterns = [
    url(r'^admin/', admin.site.urls),
url(r'^tinymce/', include('tinymce.urls')),
    url(r'^$', HomeView.as_view()),
    url(r"^watch/(?P<watch_slug>[\w-]+)/$", WatchView.as_view(), name="watch"),
    url(r'^look/(?P<look_slug>[\w-]+)/$', LookView.as_view(), name="look"),
    url(r'^listen/(?P<listen_slug>[\w-]+)/$', ListenView.as_view(), name="listen"),
    url(r'^artist/(?P<music_slug>[\w-]+)/$', ArtistView.as_view(), name="artist"),
    url(r'^radio/$', RadioView.as_view(), name="radio"),
url(r'^radio/(?P<sound_slug>[\w-]+)/$', SoundView.as_view(), name="sound"),
    url(r'^music/$', MusicView.as_view(), name="music"),
    url(r'^press/$', PressView.as_view(), name="press"),
    url(r'^events/', include('happenings.urls', namespace='calendar'), name="events"),
    url(r'^design/$', TemplateView.as_view(template_name='design.html')),
# url(r'^calendar/', include('happenings.urls', namespace='calendar')),
    url(r'^about/$', AboutView.as_view(), name="about"),
    url(r'^team/$', TeamView.as_view(), name="team"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

look/models.py
from __future__ import unicode_literals

from django.db import models
from tinymce.models import HTMLField
# Create your models here.
from django.template.defaultfilters import slugify
from home.models import HomePage
# Create your models here.
class LookPost(models.Model):
    date = models.DateTimeField()
    poster_image = models.ImageField(blank=True, null=True)
    title = models.CharField(max_length=500,blank=True, null=True)
    subtitle = models.CharField(max_length=500,blank=True, null=True)
    credits = models.CharField(max_length=500,blank=True, null=True)
    description = HTMLField(blank=True, null=True)
    slug = models.SlugField(blank=True, null=True)
    order = models.IntegerField(default=0)
    home = models.ForeignKey(HomePage, default=1)

    def __unicode__(self):
        return self.title

    def category(self):
        return "look"

    def get_url(self):
        return "/look/%s" % self.slug

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(LookPost, self).save(*args, **kwargs)

class LookImage(models.Model):
    image = models.ImageField(blank=True, null=True)
    credits = models.CharField(max_length=500, blank=True, null=True)
    description = HTMLField(blank=True, null=True)
    order = models.IntegerField(blank=True, null=True, default=0)
    post = models.ForeignKey("LookPost", null=True, blank=True)
    def __unicode__(self):
        if self.image:
            return self.image.url.split("/")[-1].split(".")[0]
        else:
            return "image"

    class Meta:
        ordering = ['order']

look/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from look.models import LookPost
from django.shortcuts import get_object_or_404


class LookView(TemplateView):
    template_name = "look.html"
    def get_context_data(self, **kwargs):
        slug = kwargs['look_slug']
        context = super(LookView, self).get_context_data(**kwargs)

        context["look"] = get_object_or_404(LookPost, slug=slug)
        context["look_more"] = LookPost.objects.exclude(pk=context["look"].pk).order_by('order').order_by(
            '-date')[:3]

        return context

look/templates/look.html
{% extends "base.html" %}
{% load site_filters %}
{% block page-class %}look-page{% endblock %}
{% block content %}

    <div class="row">

        <div class="{% cycle "col-md-12 viewport" "col-sm-6 viewport-half" "col-sm-6 viewport-half" %} {{ post.category }}"
             style="background-image: url({{ look.poster_image.url }});">
            <div class="content">
                <div class="copy-headings look-headings">
                    <div class="title">{{ look.title }}</div>
                    <div class="subtitle">{{ look.subtitle }}</div>
{#                    <span class="watch-date">{{ look.date|date:"d.m.Y" }}</span>#}
                    <div class="pull-right watch-title-logo look-category">
                                <div class="watch-logo-container pull-right">
                                    <span class="watch-date">{{ look.date|date:"d.m.Y" }}</span>
                                    <hr class="watch-date-line"/>
                                    <img src="/static/imgs/icons/{{ look.category }}-icon.svg"/>
                                </div>
                            </div>
                </div>
            </div>

        </div>

    </div>

    {% for post in look.lookimage_set.all %}

        {% if post and post.image %}
            {% row_counter as row_count %}
            {% cycle '<div class="row ">' '<div class="row ">' '' %}





            <a href="{{ post.get_url }}">
            {% if row_count == 2 and forloop.last == True %}
                    <div class="col-md-12 viewport {{ post.category }}"

                {% else %}
                    <div
                    class="{% cycle "col-md-12 viewport" "col-sm-6 viewport-half" "col-sm-6 viewport-half" %} {{ post.category }}"

                {% endif %}

                     style="background-image: url({{ post.image.url }});">


                </div>
            </a>




            {% cycle "</div>" "" "</div>" %}
            {% ifequal row_count 2 %}
                {% if forloop.last %}
                    </div>
                {% endif %}
            {% endifequal %}
        {% endif %}


    {% endfor %}
{% if look_more %}
    <div class="row watch-title">
        <div class="col-sm-12 watch-copy-body text-center" style="text-transform:uppercase"><h5>look more</h5></div>
    </div>
    <div class="row watch-copy">
        <div class="col-sm-12 watch-copy-body" style="">

                {% for more in look_more %}
                    {% if forloop.first %}
                        <a href="{{ more.get_url }}">
                            <div class="col-sm-3 watch-next-thumb"
                                 style="background-image: url({{ more.poster_image.url }});"></div>
                        </a>

                    {% else %}


                    <a href="{{ more.get_url }}">
                        <div class="col-sm-3 watch-next-thumb"
                             style="background-image: url({{ more.poster_image.url }});"></div>
                    </a>

                    {% if forloop.last %}

                    {% endif %}
                    {% endif %}
                {% endfor %}


        </div>

    </div>
    {% endif %}








{% endblock content %}